// Shared constants and labels.

const PHYSIO_HEADER_QUOTES = [
  'Let us earn that ice pack.',
  'Tiny reps, suspiciously big destiny.',
  'Mobility is calling, and it brought a clipboard.',
  'Today we negotiate with connective tissue.',
  'A little stretch, a little swagger.',
  'Your future self requested better range of motion.',
  'Time to make the joints less dramatic.',
  'Coffee later. Controlled movement now.',
  'Respect the plan. Befriend the band.',
  'We are only one set away from feeling responsible.',
  'Let us put the therapy in physiotherapy.',
  'Progress: now available in tiny increments.',
  'The resistance band believes in you, unfortunately.',
  'Joint mobility, but make it administratively satisfying.',
  'Today is sponsored by form and patience.',
  'Move gently. Log aggressively.',
  'Your tendons appreciate boring consistency.',
  'Small exercises, large main-character energy.',
  'Another glamorous day at the mobility factory.',
  'Do the set before the set does you.',
  'Stretch like someone with calendar reminders.',
  'Let us turn stiffness into paperwork.',
  'The road to recovery has excellent tracking.',
  'Nothing says wellness like counting to ten slowly.',
  'Your range of motion has entered the chat.',
  'Every rep is a tiny memo to your nervous system.',
  'Today we make discomfort file a status report.',
  'Low drama, high compliance.',
  'The body keeps score, so we made a spreadsheet.',
  'A noble quest, mostly involving elastic.',
  'Make the physio proud and the muscles confused.',
  'One controlled rep at a time, obviously.',
  'Welcome back to strategic wiggling.',
  'Your recovery arc has tasks due today.',
  'Let us knock a set off your list.',
  'Soft tissue, firm commitment.',
  'The vibes are clinical and mildly triumphant.',
  'Rehab: because momentum loves receipts.',
  'Today we collect reps like responsible adults.',
  'Some heroes wear braces and track sets.',
  'Your joints asked for a status meeting.',
  'Motion first, overthinking second.',
  'The plan is simple: move, log, repeat.',
  'Let us be brave in a very small range.',
  'Consistency: boring, effective, rude.',
  'Theraband time, naturally.',
  'Your muscles have been assigned homework.',
  'Recovery looks suspiciously like showing up.',
  'Do the tiny thing. Become slightly less creaky.',
  'Physio time: the glamorous admin of healing.',
  'Another rep, another tiny victory for cartilage.',
  'Your posture called and asked for representation.',
  'Healing is just paperwork your body files slowly.',
  'Elastic bands: humble equipment, dramatic results.',
  'Let us make stiffness regret its life choices.',
  'Controlled motion: the least flashy superpower.',
  'Today we gently bully your range of motion.',
  'Your joints deserve a well-organized comeback.',
  'Every set is a polite complaint to gravity.',
  'Stretch first, strut later.',
  'The rehab grind has excellent ankle mobility.',
  'Small moves, big physiotherapist nods.',
  'Your muscles RSVP\'d yes to accountability.',
  'Time to turn aches into action items.',
  'The band is stretchy, but our standards are not.',
  'Healing: now with more counting and less guessing.',
  'Give those tendons a reason to trust you again.',
  'Today we pursue flexibility with unreasonable optimism.',
  'Move it or lose the meeting minutes.',
  'Your shoulder has been invited to cooperate.',
  'Recovery is basically boring magic with reps.',
  'Let us make limber happen on purpose.',
  'The set tracker believes in measurable awkwardness.',
  'Your knees requested a gentle performance review.',
  'Form before flair, cartilage before chaos.',
  'Pain-free-ish is still a genre of progress.',
  'Welcome to the tiny gym of responsible decisions.',
  'Mobility gains: served lukewarm and consistent.',
  'Your body appreciates receipts, apparently.',
  'Let us stretch the truth and also the calves.',
  'Another day, another deeply professional wiggle.',
  'Your physio plan has main spreadsheet energy.',
  'Tiny movements, surprisingly bossy outcomes.',
  'The resistance band came here to negotiate.',
  'Today we make muscles read the instructions.',
  'Joint care: not glamorous, deeply productive.',
  'Put the fun in functional range, somehow.',
  'Your nervous system loves a calm repeat customer.',
  'Slow reps, quick bragging rights.',
  'Let us rehabilitate with unnecessary confidence.',
  'The mat is ready for mild excellence.',
  'Every careful rep is a peace treaty.',
  'Your future mobility sent a thank-you note.',
  'Stability: because wobbling is not a strategy.',
  'Today we charm the soft tissue with structure.',
  'Recovery has entered its cheesy montage phase.',
  'Make the movement smooth and the log smug.',
  'Your limbs have tasks, and they know it.',
  'Consistency is cheaper than complaining, usually.',
  'Physio: where tiny victories wear sensible shoes.'
];
const TRACKER_SHORTCUT_TOOLTIP = 'Right arrow completes a set. Left arrow undoes a set.';
const ARM_ANCHOR_DATE = '2026-05-01';
const ARM_ANCHOR_DAY  = 'arm-day1';
const DAY_NAMES  = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
const MONTH_ABBR = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const MONTH_NAMES = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const GROUP_ORDER = ['arm-day1', 'arm-day2', 'legs'];
const SET_TIMER_CAP_SECONDS = 60 * 60;
const DEFAULT_PERSONAL_DAY_START_TIME = '07:00';
